version: '2.3'
services:
  facenet:
    build: facenet
    runtime: nvidia
    command: sh /facenet/run_jupyter.sh
    ports:
      - 8888:8888
    volumes:
      - ./facenet:/facenet
    devices:
      - /dev/video0:/dev/video0